### ISSUE TITLE
1.0 upgrade trouble: clone fail

### ISSUE THREAD

**Issue by erikras** [kodyl/react-document-meta#2]
When upgrading to 1.0, I've got a problem where `DocumentMetaWithSideEffect.peek()` is returning `undefined` [here](https://github.com/kodyl/react-document-meta/blob/master/lib/index.js#L211), and `JSON.parse()` is falling over [here](https://github.com/kodyl/react-document-meta/blob/master/lib/utils.js#L6).

All I have to do is change
```javascript
{DocumentMeta.rewind({asReact: true})}
```
to
```javascript
{DocumentMeta.renderAsReact()}
```
Right?

**Comment by erikras** [comment]
[Here's a branch](https://github.com/erikras/react-redux-universal-hot-example/tree/react-document-meta-v1) of my project demoing the problem. Fun happening in [`/src/Html.js`](https://github.com/erikras/react-redux-universal-hot-example/blob/react-document-meta-v1/src/Html.js#L28).

**Comment by danieljuhl** [comment]
@erikras I'll look at it right away!

**Comment by danieljuhl** [comment]
@erikras I think I have found the problem. Which is actually related to the nature of React, and there is nothing I can do, as far as I see. The problem is, that your are passing un-rendered components to the Html component, and thus calling `DocumentMeta.renderAsReact()` before executing the actual content, which make the meta object empty.

I will of course fix the module, so it does not crash the app, but to actually have the server side rendering work, you will have to do something like `const content = React.renderToString(component);` before you call `DocumentMeta.renderAsReact()` and then use that content in the returned Html component. Make sense?

**Comment by danieljuhl** [comment]
```js
  render() {
    const {assets, component, store} = this.props;
    const content = React.renderToString(component);

    return (
      <html lang="en-us">
        <head>
          <meta charSet="utf-8"/>
          {DocumentMeta.renderAsReact()}

          <link rel="shortcut icon" href="/favicon.ico" />
          <link href={cdn + 'twitter-bootstrap/3.3.5/css/bootstrap.css'}
                media="screen, projection" rel="stylesheet" type="text/css" />
          <link href={cdn + 'font-awesome/4.3.0/css/font-awesome.min.css'}
                media="screen, projection" rel="stylesheet" type="text/css" />

          {/* styles (will be present only in production with webpack extract text plugin) */}
          {Object.keys(assets.styles).map((style, i) =>
            <link href={assets.styles[style]} key={i} media="screen, projection"
                  rel="stylesheet" type="text/css"/>
          )}
        </head>
        <body>
          <div id="content" dangerouslySetInnerHTML={{__html: content}}/>
          <script dangerouslySetInnerHTML={{__html: `window.__data=${serialize(store.getState())};`}} />
          <script src={assets.javascript.main}/>
        </body>
      </html>
    );
```

**Comment by danieljuhl** [comment]
v1.0.1 fixes the crashing

**Comment by erikras** [comment]
Yes, that makes sense. I'm having [similar SSR problems](https://github.com/acdlite/redux-react-router/issues/14) with `redux-react-router`, which expects the `render()` to generate its data.

Thanks!
